forcenedorProj/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedor/', include('fornecedor.urls')),
]

fornecedor/urls.py
from django.urls import path,re_path
from . import views
from django.urls import reverse
app_name = 'fornecedor'

urlpatterns = [
    
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'add/', views.FornecedorCreate.as_view(), name='fornecedor-add'),
    re_path(r'^(?P<pk>[0-9]+)/update/$', views.FornecedorUpdate.as_view(), name='fornecedor-update'),
    re_path(r'^(?P<pk>[0-9]+)/delete/$', views.FornecedorDelete.as_view(), name='fornecedor-delete'),   
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
     
]

fornecedor/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Fornecedor(models.Model):
    CNPJ = models.CharField(max_length=18)
    nome = models.CharField(max_length=100)
    is_ativo = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('fornecedor:detail',kwargs ={'pk':self.pk})

    def __str__(self):
        return self.nome

class Produto(models.Model):
    fornecedor = models.ForeignKey(Fornecedor,on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

fornecedor/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Fornecedor,Produto
from django.urls import reverse
# from django.http import HttpResponse


class IndexView(generic.ListView):
    template_name = 'fornecedor/index.html'
    context_object_name = 'all_fornecedores'
    def get_queryset(self):
        return Fornecedor.objects.all().order_by("nome")

class DetailView(generic.DetailView):
    model = Fornecedor
    template_name = 'fornecedor/detail.html'

class FornecedorCreate(CreateView):
    model = Fornecedor
    fields = ['CNPJ','nome','is_ativo']

class FornecedorUpdate(UpdateView):
    model = Fornecedor
    fields = ['CNPJ','nome','is_ativo']

class FornecedorDelete(DeleteView):
    model = Fornecedor
    success_url = reverse('fornecedor:index')
    # def get_success_url():
    #     return reverse('fornecedor:index')

fornecedor/templates/fornecedor/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Load the path to your static files -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'fornecedor/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script> <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fornex {% block title %}{% endblock %}</title>
</head>
<body>
    
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'fornecedor:index' %}">Fornex</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(página atual)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Ação</a>
                        <a class="dropdown-item" href="#">Outra ação</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Algo mais aqui</a>
                      </div>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link " href="{% url 'fornecedor:fornecedor-add'%}">Add Fornecedor</a>
                    </li>
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
                  </form>
                </div>
              </nav>

              {% block body %}
              {% endblock %}
</body>
</html>

fornecedor/templates/fornecedor/detail.html
{% extends 'fornecedor/base.html' %}
{% block title %} - {{fornecedor.nome}} {% endblock %}
{% block body %}
<h1>{{fornecedor.nome}}</h1>
<h3>CNPJ: {{fornecedor.CNPJ}}</h3>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'fornecedor:detail' fornecedor.id %}" method="POST">
    {% csrf_token %} 
    {% if fornecedor.is_ativo %}
    <input type="checkbox" id="active" name="active" checked value="{{ fornecedor.is_ativo }}">
    
        <label for="active">           
            <strong>Ativo</strong>
        </label><br>
        <input type="submit" value="Desativar">
            {% else %}
            <input type="checkbox" id="active" name="active" value="{{ fornecedor.is_ativo }}">
    
            <label for="active">           
                <strong>Ativo</strong>
            </label><br>
            <input type="submit" value="Ativar">
        {% endif %}        
    
</form>

<h3>Produtos:</h3>
<ul>
    {% for produto in fornecedor.produto_set.all %}
        <li>{{ produto.nome }}</li>
    {% endfor %}
</ul>
{% endblock %}

fornecedor/templates/fornecedor/form-template.html
{% for field in form %}
    <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
            <label class="control-label col-sm-2">{{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

fornecedor/templates/fornecedor/fornecedor_form.html
{% extends 'fornecedor/base.html' %}
{% block title %} - Add Fornecedor {% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'fornecedor/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Salvar</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

fornecedor/templates/fornecedor/index.html
{% extends 'fornecedor/base.html' %}
{% block body %}
{% if all_fornecedores %}
<h3>Fornecedores:</h3>
<ul>
    {% for fornecedor in all_fornecedores %}
    <li><a href="{% url 'fornecedor:detail' fornecedor.id %}">{{ fornecedor.nome}}</a> 
        (<a href="{% url 'fornecedor:fornecedor-delete'%} ">delete</a>,
        <a href="{% url 'fornecedor:fornecedor-update'%} ">update</a>)</li>
    {% endfor %}
</ul>
{% else %}
<h3>Você não tem nenhum Fornecedor</h3>
{% endif %}
{% endblock %}